### ISSUE TITLE
Интеграция sendpulse

### ISSUE THREAD

**Issue by ZhdanovO** [olegsklyarov/self-control-diary#101]
* [x] регистрация на сервисе https://sendpulse.com/ru ([бесплатно](https://sendpulse.com/ru/prices) до 500 подписчиков и до 1500 писем)
* [ ] Настройка книги для отправки писем о регистрации

**Comment by olegsklyarov** [comment]
@ZhdanovO , все-таки не https://mailchimp.com?

**Comment by ZhdanovO** [comment]
Метод запроса REST API POST
https://events.sendpulse.com/events/name/verifikaciya_email
Необходима авторизация по API-ключам
{
  "email": "some@mail.com",
  "phone": "+123456789",
  "verification_url": "verification_url value"
}

https://login.sendpulse.com/emailservice/automation/flow/id/26118/

**Comment by olegsklyarov** [comment]
Задача выполнена. Sendpulse делает свое дело хорошо. Книгу можно не создавать, это нам не требуется
