### ISSUE TITLE
README.md в корне проекта

### ISSUE THREAD

**Issue by olegsklyarov** [olegsklyarov/self-control-diary#56]
Написать инструкцию как развернуть проект с нуля (установка зависимостей, создать файлы .env.local и .env.test, подключение к БД, создание структуры БД, миграции, запуск тестов)

**Comment by yurylook** [comment]
Настройка проекта.
1. Устанавливаем на компьютер локальный Веб-сервер "OpenServer" (можно по ссылке https://ospanel.io/download/ ).
   Заходим в созданный  каталог и запускаем файл Open Server.exe. После старта программы вы увидите красный флажок 
   в области уведомлений Windows (область возле системных часов). 
   Чтобы включить непосредственно сам веб-сервер и сопутствующие модули нажмите на флажок, далее
   выполните [Меню → Запустить].
   Если антивирус пытается заблокировать процесс ,везде жмём разрешить.
   Сервер запущен успешно если флажок сменил цвет с красного на зеленый.
2. Запускаем cmder и открываем заранее созданную под проект  папку. Клонируем проект в эту папку по ссылке  
   https://github.com/olegsklyarov/self-control-diary.
3. Заходим в меню OpenServer (кликаем на зеленый флажок и открываем консоль (меню -> дополнительно -> консоль). 
   Далее через команды консоли встаем на папку проекта.    
4. Проверяем ,что запускается команда php -v ,а затем команда composer --version.	
5. Заходим в папку проекта и проверяем что в корневом каталоге лежат  файлы с переменными окружения .env  .env.local
   .env.test.
   Затем в консоли запускаем команду сomposer install.
6. Заходим в меню OpenServer (кликаем на зеленый флажок и открываем  (меню -> настройки -> модули). 
   Выбираем HTTP :  Apache_2.4PHP_7.2-7.4 
            PHP: PHP_7.4  
            PostgreSQL-12.2
   Сохраняем настройки и перезагружаем OpenServer.
7. Затем в консоли запускаем команду php bin/console d:d:c (Эта команда создаёт базу данных в Postgres) 
   и команду  php bin/console d:m:m (Эта команда создаёт Таблицы в базе данных).
8. Запускаем тесты командой composer run-script test.   
   Если первый тест не прошел (x ApiDiaryDeleteCest: Test DELETE /api/diary/{noted_at} (cascade) (7.41s))
   то повторяем команду  composer run-script test.
   Если все прошло успешно получаем сообщение OK (23 tests, 93 assertions).

9. Пробуем накатить текстовые данные : 
   Заходим в меню OpenServer (кликаем на зеленый флажок и открываем  (меню -> дополнительно -> конфигурация ). 
   Кликаем на PHP_7.4 . В результате этого в редакторе откроется файл php.ini . Находим строку  extension = pgsql
   и раскомментируем её удалив символ ; в начале строки. Жмем сохранить и перезапускаем OpenServer.
   Затем в консоли запускаем команду php bin/console doctrine:fixtures:load (выбираем yes). 
   Заходим в меню OpenServer (кликаем на зеленый флажок и открываем  (меню -> дополнительно -> phpPgAdmin ).
   Нажимаем на него и попадаем на страницу phpPgAdmin  http://127.0.0.1/openserver/phppgadmin/index.php
   Кликаем по ссылке PostgreSQL далее в поле имя пользователя вводим postgres и заходим в БД.

10. Если в дальнейшем надо будет cнова  запустиь тесты  composer run-script test    
    то нужно почистить базу, для этого нужно запустить команды:
	php bin/console doctrine:database:drop --force (удалить БД)
	php bin/console doctrine:database:create (создать БД)
	php bin/console doctrine:migrations:migrate (создать пустые талблцы БД)
