### ISSUE TITLE
DELETE /api/mencho/samaya/{noted_at}/{mantra_uuid}

### ISSUE THREAD

**Issue by olegsklyarov** [olegsklyarov/self-control-diary#64]
1. Написать MenchoSamayaResolver, который вынимает запись из таблицы `mencho_samaya` по `diary.noted_at` + `mantra_uuid`
2. Добавить метод **delete**, который получает на вход `MenchoSamaya $menchoSamaya`
2. Если `$menchoSamaya === null`, то возвращаем `404`
3. Удаляем из таблицу `menсho_samaya` найденную запись. Метод возвращает `204` (No Content).
4. Написать функциональный тест на все описанные кейсы

**Comment by ZhdanovO** [comment]
Сделать тесты на не верный UUID и Diary и не авторизован.

**Comment by olegsklyarov** [comment]
@ZhdanovO, ждём pull request
